// Lady Wolfpack HQ -- practice schedule. Edit this file to add/update practices.
const PRACTICES = [
    {m:"September 2026", day:"Tue", date:"Sep 8", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 9", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 9", time:"6:45–7:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Thu", date:"Sep 10", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Tue", date:"Sep 15", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 16", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 16", time:"6:45–7:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Thu", date:"Sep 17", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Tue", date:"Sep 22", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 23", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 23", time:"6:45–7:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Thu", date:"Sep 24", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Tue", date:"Sep 29", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"September 2026", day:"Wed", date:"Sep 30", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},

    {m:"October 2026", day:"Thu", date:"Oct 1", time:"5:25–6:10 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 1", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Tue", date:"Oct 6", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Wed", date:"Oct 7", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 8", time:"5:25–6:10 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 8", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Tue", date:"Oct 13", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Wed", date:"Oct 14", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 15", time:"5:25–6:10 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 15", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Tue", date:"Oct 20", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Wed", date:"Oct 21", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 22", time:"5:25–6:10 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 22", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Tue", date:"Oct 27", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Wed", date:"Oct 28", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 29", time:"5:25–6:10 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"October 2026", day:"Thu", date:"Oct 29", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},

    {m:"November 2026", day:"Tue", date:"Nov 3", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Wed", date:"Nov 4", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 5", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 5", time:"7:45–8:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Tue", date:"Nov 10", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Wed", date:"Nov 11", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 12", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 12", time:"7:45–8:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Tue", date:"Nov 17", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Wed", date:"Nov 18", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 19", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 19", time:"7:45–8:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Tue", date:"Nov 24", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Wed", date:"Nov 25", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Thu", date:"Nov 26", time:"6:30–7:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"November 2026", day:"Mon", date:"Nov 30", time:"7:50–8:50 PM", session:"Practice", loc:"Champions Skating Center", optional:false},

    {m:"December 2026", day:"Tue", date:"Dec 1", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 2", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 2", time:"6:45–7:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Tue", date:"Dec 8", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 9", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 9", time:"6:45–7:30 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Tue", date:"Dec 15", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 16", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Tue", date:"Dec 22", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 23", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Tue", date:"Dec 29", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"December 2026", day:"Wed", date:"Dec 30", time:"7:40–8:40 PM", session:"Practice", loc:"Champions Skating Center", optional:false},

    {m:"January 2027", day:"Tue", date:"Jan 5", time:"5:30–6:15 PM", session:"Dry Land Training", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Tue", date:"Jan 5", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Wed", date:"Jan 6", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Tue", date:"Jan 12", time:"7:50–8:50 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Wed", date:"Jan 13", time:"7:30–8:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Tue", date:"Jan 19", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Wed", date:"Jan 20", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Tue", date:"Jan 26", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"January 2027", day:"Wed", date:"Jan 27", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},

    {m:"February 2027", day:"Tue", date:"Feb 2", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Wed", date:"Feb 3", time:"5:30–6:30 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Tue", date:"Feb 9", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Wed", date:"Feb 10", time:"7:00–8:00 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Tue", date:"Feb 16", time:"5:30–6:30 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Wed", date:"Feb 17", time:"6:40–7:40 PM", session:"Practice", loc:"Champions Skating Center", optional:false},
    {m:"February 2027", day:"Tue", date:"Feb 23", time:"6:40–7:40 PM", session:"Skills", loc:"Champions Skating Center", optional:false},
  ];
